version: '3.8'

services:
  loki:
    image: grafana/loki:2.9.3
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
    networks:
      - observability

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_SECURITY_ALLOW_EMBEDDING=true
    volumes:
      - ./configs/grafana/datasources/datasource.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - ./configs/grafana/dashboards:/etc/grafana/provisioning/dashboards
    networks:
      - observability
    depends_on:
      - loki

  rabbitmq:
    image: rabbitmq:3-management
    ports:
        - "5672:5672"
        - "15672:15672"
    environment:
        - RABBITMQ_DEFAULT_USER=guest
        - RABBITMQ_DEFAULT_PASS=guest
    networks:
        - observability

networks:
  observability:
    driver: bridge

volumes:
  loki-data:
  grafana-data: