{
 "title": "DDD Online Shop Metriken",
 "time": { "from": "2025-10-26T09:11:47.692Z", "to": "2025-10-26T13:07:08.468Z" },
 "panels": [
  {
   "title": "Domain-Event-Verarbeitungszeit (s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(domain_event_processing_seconds_sum[5m])) by (event_type) / sum(rate(domain_event_processing_seconds_count[5m])) by (event_type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Verarbeitete Domain-Events pro Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(domain_events_processed_total[5m])) by (event_type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Durchschnittliche Antwortzeit (s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_sum[5m])) by (path) / sum(rate(http_server_request_duration_seconds_count[5m])) by (path)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API-Requests per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count[5m])) by (path)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Domain-Event-Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=\"productcatalog-api\"} |= \"Domain Event\""
    }
   ]
  },
  {
   "title": "Error-Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=\"productcatalog-api\"} |~ \"ERR|Error\""
    }
   ]
  },
  {
   "title": "ProductCatalog API Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=\"productcatalog-api\"}"
    }
   ]
  }
 ]
}